"""
rep.py — Report generator for VAMPS output files.

Port of rep.sl.  Reads a VAMPS .out file and writes a human-readable
report summarising the run metadata, initial profile, and water balance.

Usage from a script::

    from rep import rep
    rep("run.out", "run.rep")

Or from the command line::

    python rep.py run.out run.rep
"""

import sys


def _parse_out(filename):
    """Parse a VAMPS .out file into {section: {key: value_or_list}}."""
    sections = {}
    current = None
    current_key = None
    current_val = []

    def flush():
        nonlocal current_key, current_val
        if current is not None and current_key is not None:
            v = current_val
            sections[current][current_key] = v[0] if len(v) == 1 else v
        current_key = None
        current_val = []

    def _convert(s):
        try:
            return int(s)
        except ValueError:
            pass
        try:
            return float(s)
        except ValueError:
            return s

    with open(filename) as fh:
        for raw in fh:
            line = raw.rstrip('\n')
            stripped = line.strip()

            if stripped.startswith('#') or stripped == '':
                if not (current_key and raw.rstrip().endswith('\\')):
                    flush()
                continue

            if stripped.startswith('[') and stripped.endswith(']'):
                flush()
                current = stripped[1:-1]
                sections.setdefault(current, {})
                continue

            if current is None:
                continue

            if current_key is not None and '=' not in stripped.split('#')[0]:
                cont = stripped.rstrip('\\').split()
                current_val.extend(_convert(v) for v in cont)
                if not stripped.rstrip().endswith('\\'):
                    flush()
                continue

            if '=' in stripped:
                flush()
                eq = stripped.index('=')
                key = stripped[:eq].strip()
                rest = stripped[eq + 1:].strip()
                if '#' in rest:
                    rest = rest[:rest.index('#')].strip()
                cont_line = rest.endswith('\\')
                if cont_line:
                    rest = rest[:-1].strip()
                current_key = key
                current_val = [_convert(v) for v in rest.split() if v]
                if not cont_line:
                    flush()

    flush()
    return sections


def rep(infile, outfile=None):
    """Write a human-readable report of *infile* to *outfile*.

    Parameters
    ----------
    infile  : str   path to a VAMPS .out file
    outfile : str   destination report file (default: stdout)
    """
    sects = _parse_out(infile)

    def g(section, key, default="NOT FOUND"):
        v = sects.get(section, {}).get(key, default)
        if isinstance(v, list):
            return " ".join(str(x) for x in v)
        return str(v)

    lines = []
    w = lines.append

    w(f"Report of the file {infile} generated by rep.py")
    w("GENERAL" + "-" * 65)
    w("The command that generated this file was:")
    w(f"  {g('header', 'command')}")
    w(f"Run started at:  {g('header', 'run_start_time')}")
    w(f"Run ended at:    {g('trailer', 'run_end_time')}")
    w(f"Total iterations:           {g('final', 'nr_it')}")
    w(f"Total timestep calls:       {g('final', 'timestep_calls')}")
    w(f"Total tridiag calls:        {g('final', 'nr_tri')}")
    w(f"Total banddiag calls:       {g('final', 'nr_band')}")
    w(f"Total saturation calls:     {g('final', 'nr_sat')}")

    w("\nINITIAL" + "-" * 65)
    w(f"Initial water volume of profile:    {g('initial', 'volini')}")
    w(f"Saturated water volume of profile:  {g('initial', 'volsat')}")

    w("\nTIME" + "-" * 68)
    w(f"Number of timesteps in run:  {g('initial', 'steps')}")

    w("\nSOIL" + "-" * 68)
    w(f"Total soil layers:  {g('initial', 'layers')}")

    w("\nINITIAL PROFILE" + "-" * 57)
    z     = sects.get("initial", {}).get("z",     [])
    h     = sects.get("initial", {}).get("h",     [])
    k     = sects.get("initial", {}).get("k",     [])
    theta = sects.get("initial", {}).get("theta", [])
    ksat  = sects.get("initial", {}).get("ksat",  [])
    if not isinstance(z, list):
        z, h, k, theta, ksat = [z], [h], [k], [theta], [ksat]
    w(f"{'z':>10}  {'theta':>10}  {'h':>14}  {'k':>12}  {'ksat':>12}")
    for i in range(len(z)):
        zv     = z[i]     if i < len(z)     else "?"
        tv     = theta[i] if i < len(theta) else "?"
        hv     = h[i]     if i < len(h)     else "?"
        kv     = k[i]     if i < len(k)     else "?"
        ksatv  = ksat[i]  if i < len(ksat)  else "?"
        w(f"{zv:>10.4f}  {tv:>10.6f}  {hv:>14.6f}  {kv:>12.6f}  {ksatv:>12.6f}")

    w("\nWATER BALANCE SUMMARY" + "-" * 51)
    w(f"Total precipitation:    {g('final', 'precipitation')}")
    w(f"Total transpiration:    {g('final', 'transpiration')}")
    w(f"Total interception:     {g('final', 'interception')}")
    w(f"Total soilevaporation:  {g('final', 'soilevaporation')}")
    w(f"Total rootextraction:   {g('final', 'rootextract')}")
    w(f"Total drainage:         {g('final', 'drainage')}")
    w(f"Total surface_runoff:   {g('final', 'surface_runoff')}")
    w(f"Initial storage:        {g('final', 'initial_storage')}")
    w(f"Final storage:          {g('final', 'final_storage')}")
    w(f"Change in storage:      {g('final', 'delta_storage')}")
    w(f"Mass-balance error:     {g('final', 'mass_balance')}")

    w("\nINPUT FILE" + "-" * 62)
    inp = g('header', 'infilename')
    try:
        with open(inp) as fh:
            w(fh.read())
    except OSError:
        w(f"(could not read input file: {inp})")

    text = "\n".join(lines) + "\n"

    if outfile:
        with open(outfile, 'w') as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: rep.py infile.out [outfile.rep]", file=sys.stderr)
        sys.exit(1)
    rep(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
